# Generated by Django 5.0.7 on 2024-08-22 10:02

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    for category in Category.objects.all():
        unique_slug = slugify(category.name)
        counter = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slugify(category.name)}-{counter}'
            counter += 1
        category.slug = unique_slug
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_category_options_product_is_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default-slug", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
