# Generated by Django 5.0.7 on 2024-08-25 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_wishlistitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="user",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
