# Generated by Django 5.0.7 on 2024-08-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="telephone",
            field=models.CharField(default="Not Provided", max_length=15),
        ),
    ]
